---
title: "Second Week Activities"
author: "OscarAMtz"
date: "28 de enero de 2019"
output: html_document
---
## Second Week
##
## directory used: "c:/Users/OscarAMtz/Desktop/specdata"
### First Assingment
```{r}
dir <- "c:/Users/OscarAMtz/Desktop/specdata"

pollutantmean <- function(directory, pollutant, id = 1:332){
  ## Reading Data
  files <- list.files(directory, full.names = TRUE)
  pt <- lapply(files[id], read.csv)
  mpt <- do.call(rbind, pt)
  mean(mpt[,pollutant == names(mpt)], na.rm = TRUE)
}

pollutantmean(dir, "sulfate", id = 1:10)
pollutantmean(dir, "nitrate", 70:72)
pollutantmean(dir, "nitrate", 23)
```

### Second assigment

```{r}
dir <- "c:/Users/OscarAMtz/Desktop/specdata"
complete <- function(directory, id = 1:332){
  ## Reading data
  files <- list.files(directory, full.names = TRUE)
  pt <- lapply(files[id], read.csv)
  mpt <- do.call(rbind, pt)
  output <- data.frame()
  for (i in id){
    idmpt <- mpt[mpt$ID == i,]
    compt <- complete.cases(idmpt)
    rows <- sum(compt)
    output <- rbind(output, c(i, rows))
  }
  colnames(output)  <- c("id","nobs")
  output
}
complete(dir, c(2, 4, 8, 10, 12))
complete(dir, 30:25)
complete(dir, 3)

##Solución alternativa

```


### Third assignment 

```{r}
dir <- "c:/Users/OscarAMtz/Desktop/specdata"
corr <- function(directory, threshold = 0){
  ## Getting IDs complete cases number of rows
  ccases <- complete(directory)
  mtthres <- ccases[ccases$nobs > threshold,"id"]
  ## Reading data
  files <- list.files(directory, full.names = TRUE)
  pt <- lapply(files, read.csv)
  mpt <- do.call(rbind, pt)
  ## Complete cases
  mpt_cc <- mpt[complete.cases(mpt),]
  correlation <- vector()
      for (i in mtthres){
          mptcc_fcor <- cor(mpt_cc[mpt_cc$ID == i,2], mpt_cc[mpt_cc$ID == i,3])
          correlation <- c(correlation, mptcc_fcor)
        }
  correlation
}

cr <- corr(dir, threshold = 150)
head(cr)
summary(cr)
length(cr)
cr <- corr(dir, threshold = 400)
head(cr)
summary(cr)
length(cr)
cr <- corr(dir, threshold = 5000)
head(cr)
summary(cr)
length(cr)
cr <- corr(dir, 0)
head(cr)
summary(cr)
length(cr)
```
<<<<<<< HEAD
<<<<<<< HEAD

## Quiz
#1
```{r}
pollutantmean(dir, "sulfate", 1:10)
```
#2
```{r}
pollutantmean(dir, "nitrate", 70:72)
```
#3
```{r}
pollutantmean(dir, "sulfate", 34)
```
#4
```{r}
pollutantmean(dir, "nitrate")
```
#5
```{r}
cc <- complete(dir, c(6, 10, 20, 34, 100, 200, 310))
print(cc$nobs)
```
#6
```{r}
cc <- complete(dir, 54)
print(cc$nobs)
```
#7
```{r}
set.seed(42)
cc <- complete(dir, 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])
```
#8
```{r}
cr <- corr(dir)                
cr <- sort(cr)                
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)
```
#9
```{r}
cr <- corr(dir, 129)                
cr <- sort(cr)                
n <- length(cr)                
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```
#10
```{r}
cr <- corr(dir, 2000)                
n <- length(cr)                
cr <- corr(dir, 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

=======
>>>>>>> 4256aa5aa22cfac80b8f97ea7278c7cc47061e4d
=======
>>>>>>> 4256aa5aa22cfac80b8f97ea7278c7cc47061e4d
